services:
  web:
    image: beeman/static-server:latest
    volumes:
      - ./dist:/workspace/app:ro
    ports:
      - "9886:9876"
    environment:
      - SPA=true
  www:
    image: beeman/static-server:latest
    environment:
      - REDIRECT_URL=https://shadow.colmena.dev
