services:
  web:
    image: beeman/static-server:latest
    volumes:
      - ./dist:/workspace/app:ro
    environment:
      - SPA=true
    networks:
      - dokploy-network
  www:
    image: beeman/static-server:latest
    environment:
      - REDIRECT_URL=https://shadow.colmena.dev
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
